In [1]:
# Question 1

x <- sample(1:6,10,replace=T)
for (i in x){
    print(x[i])
} 

[1] 1
[1] 1
[1] 5
[1] 5
[1] 5
[1] 1
[1] 5
[1] 1
[1] 1
[1] 5


In [2]:
# Question 2

sample_data <- sample(1:6,10,replace=T)
print(sample_data)

sample_space <- matrix(0, nrow=6, ncol=6)

for (ind in 2:length(sample_data)-1) {
    curEle <- sample_data[ind]
    nexEle <- sample_data[ind+1]
    sample_space[[curEle,nexEle]] = sample_space[[curEle,nexEle]] + 1
}
print(sample_space)

 [1] 4 4 2 3 5 2 2 2 3 6
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    0    0    0    0    0    0
[2,]    0    2    2    0    0    0
[3,]    0    0    0    0    1    1
[4,]    0    1    0    1    0    0
[5,]    0    1    0    0    0    0
[6,]    0    0    0    0    0    0


In [3]:
# Question 3

sample_data <- sample(1:6,5000,replace=T)
sample_space <- matrix(0, nrow=6, ncol=6)

for (ind in 2:length(sample_data)-1) {
    curEle <- sample_data[ind]
    nexEle <- sample_data[ind+1]
    sample_space[[curEle,nexEle]] = sample_space[[curEle,nexEle]] + 1
}

sample_space_prob <- matrix(0, nrow=6, ncol=6)
for (sample_index in 1:6) {
    element_count <- 0
    for (eleIndex in 1:6) {
        element_count = element_count + sample_space[[sample_index, eleIndex]]
    }
    for (sample_number in 1:6) {
        sample_space_prob[[sample_index, sample_number]] = sample_space[[sample_index, sample_number]] / element_count

    }       
}

# print("### Sample Data ###")
# print(sample_data)
print("### Sample Space ###")
print(sample_space)
print("### Sample Space Probablity ###")
print(sample_space_prob)

[1] "### Sample Space ###"
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]  126  150  135  120  128  129
[2,]  125  139  167  142  141  153
[3,]  145  154  142  162  131  124
[4,]  141  152  145  122  137  145
[5,]  125  147  115  149  137  140
[6,]  126  125  154  147  139  140
[1] "### Sample Space Probablity ###"
          [,1]      [,2]      [,3]      [,4]      [,5]      [,6]
[1,] 0.1598985 0.1903553 0.1713198 0.1522843 0.1624365 0.1637056
[2,] 0.1441753 0.1603230 0.1926182 0.1637832 0.1626298 0.1764706
[3,] 0.1689977 0.1794872 0.1655012 0.1888112 0.1526807 0.1445221
[4,] 0.1674584 0.1805226 0.1722090 0.1448931 0.1627078 0.1722090
[5,] 0.1537515 0.1808118 0.1414514 0.1832718 0.1685117 0.1722017
[6,] 0.1516245 0.1504212 0.1853189 0.1768953 0.1672684 0.1684717
